name: SauvetageExpress
version: '${project.version}'
main: fr.etercube.sauvetageexpress.Main
api-version: '1.19'
softdepend:
  - 'EterEvents'
loadbefore:
  - 'EterEvents'
authors: [Trisout78]
commands:
  sauvetageexpress:
    description: Controls the sauvetageexpress game
    usage: /sauvetageexpress <start|stop|bypassiv>
    permission: sauvetageexpress.command