name: DontKillYourself
version: '${project.version}'
main: fr.etercube.dontkillyourself.Main
api-version: '1.19'
softdepend:
  - 'EterEvents'
loadbefore:
  - 'EterEvents'
authors: [Trisout78]
commands:
  dontkillyourself:
    description: Controls the DontKillYourself game
    usage: /dontkillyourself <start|stop>
    permission: dontkillyourself.command